/**
 * Save generated bytes to disk from a tool.
 *
 * The Tauri webview has no download handler, so wry answers every
 * `<a download>` navigation with `WKNavigationActionPolicy::Cancel` — anchor
 * downloads (file-saver included) are silently dropped in the desktop app.
 * On desktop we therefore ask for a path with the native Save dialog and write
 * the bytes ourselves; on web the anchor download stays the only option.
 *
 * Returns false when the user dismissed the Save dialog; throws when the write
 * itself fails, so callers can surface the reason.
 */
import { isDesktop } from "./is-desktop"

export async function saveFile(
  data: Uint8Array | string,
  filename: string,
  mime = "application/octet-stream",
): Promise<boolean> {
  if (isDesktop()) {
    const { save } = await import("@tauri-apps/plugin-dialog")
    const path = await save({ defaultPath: filename })
    if (!path) return false
    const { writeFile, writeTextFile } = await import("@tauri-apps/plugin-fs")
    if (typeof data === "string") await writeTextFile(path, data)
    else await writeFile(path, data)
    return true
  }

  const url = URL.createObjectURL(new Blob([data as BlobPart], { type: mime }))
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  // Revoke on the next tick — revoking synchronously can race the download.
  setTimeout(() => URL.revokeObjectURL(url), 0)
  return true
}
